#!/bin/bash

# check_snmp_dellpdu

## Defaults
HOSTNAME=
SNMP_VERSION=1
COMMUNITY=public
OUTPUT_PERFDATA=false
TIMEOUT=1
RETRY=1
TYPE_CHECK=

WARN_THRESHOLD=
CRIT_THRESHOLD=
THRESHOLDS_SET=false

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
OUTPUT_DETAIL=
RET_CODE=$OK

# Used to check for connectrivity
sysDescr=".1.3.6.1.2.1.1.1.0"
#productStatus = Status
productStatusGlobalStatus=".1.3.6.1.4.1.674.10903.200.2.110.1.0"
productStatusLastGlobalStatus=".1.3.6.1.4.1.674.10903.200.2.110.1.0"
#rPDU -> rPDUIdentD = info

#rPDU -> rPDUDevice = load

#rPDU -> rPDUIdentD = phase

function help ()
{
	echo "use : $0 -H hostname -C community -x type_check -w ## -c ##"
	echo ""
	echo "  -H  : hostname or IP address of ups device"
	echo "  -C  : snmp community (default:public)"
	echo ""
	echo "  -x : type_check options"
	echo "		info		Display information on detected PDU's"
	echo "		status	Global status"
	echo "		load		Device Load in kW"
	echo "		phase	Loads by Phase in Amps"
	echo ""
	echo "  -w  : Warning threshhold"
	echo "  -c  : Critical threshold"
	echo ""
	echo "  -h  : print this message"
	exit $UNKNOWN
}
